# Generated by Django 5.2.6 on 2025-10-29 02:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='방 이름')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='방 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('max_members', models.PositiveIntegerField(default=100, verbose_name='최대 인원')),
                ('is_private', models.BooleanField(default=False, verbose_name='비공개 방')),
                ('password', models.CharField(blank=True, max_length=20, verbose_name='방 비밀번호')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL, verbose_name='방 생성자')),
            ],
            options={
                'verbose_name': '채팅방',
                'verbose_name_plural': '채팅방들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('message_type', models.CharField(choices=[('text', '일반 텍스트'), ('image', '이미지'), ('file', '파일'), ('system', '시스템 메시지'), ('join', '입장 알림'), ('leave', '퇴장 알림')], default='text', max_length=10, verbose_name='메시지 타입')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='수정일시')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='삭제 여부')),
                ('file_url', models.URLField(blank=True, verbose_name='파일 URL')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chat.chatmessage', verbose_name='답장 대상')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='채팅방')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지들',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_file_upload', models.BooleanField(default=True, verbose_name='파일 업로드 허용')),
                ('allow_image_upload', models.BooleanField(default=True, verbose_name='이미지 업로드 허용')),
                ('message_retention_days', models.PositiveIntegerField(default=30, verbose_name='메시지 보관 기간(일)')),
                ('slow_mode_seconds', models.PositiveIntegerField(default=0, help_text='0이면 비활성화', verbose_name='슬로우 모드(초)')),
                ('auto_delete_messages', models.BooleanField(default=False, verbose_name='메시지 자동 삭제')),
                ('welcome_message', models.TextField(blank=True, verbose_name='환영 메시지')),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='chat.chatroom', verbose_name='채팅방')),
            ],
            options={
                'verbose_name': '채팅방 설정',
                'verbose_name_plural': '채팅방 설정들',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='프로필 사진')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='자기소개')),
                ('is_online', models.BooleanField(default=False, verbose_name='온라인 상태')),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now, verbose_name='마지막 활동')),
                ('preferred_language', models.CharField(default='ko', max_length=10, verbose_name='선호 언어')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
            },
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='입장일시')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='마지막 접속')),
                ('is_online', models.BooleanField(default=False, verbose_name='온라인 상태')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 권한')),
                ('nickname', models.CharField(blank=True, max_length=30, verbose_name='방 내 닉네임')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.chatroom', verbose_name='채팅방')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_rooms', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '방 멤버',
                'verbose_name_plural': '방 멤버들',
                'ordering': ['-joined_at'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
