# Generated by Django 5.2.6 on 2025-10-30 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='is_online',
        ),
    ]
