# Generated by Django 5.2.6 on 2025-10-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_roommember_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', '일반 텍스트'), ('image', '이미지'), ('file', '파일'), ('system', '시스템 메시지')], default='text', max_length=10, verbose_name='메시지 타입'),
        ),
    ]
