# Generated by Django 5.2.6 on 2025-10-31 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatmessage'),
        ),
    ]
