# Generated by Django 5.2.6 on 2025-10-31 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_roommember_last_read_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommember',
            name='last_read_message',
        ),
    ]
