# Generated by Django 5.2.6 on 2025-11-03 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_roommember_last_read_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatmessage', verbose_name='마지막으로 읽은 메시지'),
        ),
    ]
