# Generated by Django 5.2.6 on 2025-11-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_roommember_last_read_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='total_members_at_time',
            field=models.PositiveIntegerField(default=0, verbose_name='메시지 전송 당시 총 멤버 수'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='unread_count',
            field=models.PositiveIntegerField(default=0, verbose_name='안 읽은 수'),
        ),
    ]
