# Generated by Django 5.2.6 on 2025-11-03 03:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chatmessage_total_members_at_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='is_currently_in_room',
            field=models.BooleanField(default=False, verbose_name='현재 방에 접속 중'),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='방 마지막 접속'),
        ),
    ]
