# Generated by Django 5.2.6 on 2025-11-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_roommember_is_currently_in_room_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoomSettings',
        ),
    ]
