# Generated by Django 5.2.6 on 2025-11-03 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_delete_chatroomsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'like'), ('good', 'good'), ('check', 'check')], max_length=50, verbose_name='반응유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='반응일시')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to='chat.chatmessage', verbose_name='메시지')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reactions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '메시지 반응',
                'verbose_name_plural': '메시지 반응들',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message', 'reaction_type'], name='chat_messag_message_b87cb7_idx')],
                'unique_together': {('user', 'message', 'reaction_type')},
            },
        ),
    ]
