# Generated by Django 5.2.6 on 2025-11-06 05:46

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_messagereaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='file_url',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.upload_to),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
