# Generated by Django 5.2.6 on 2025-11-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_chatmessage_file_url_chatmessage_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='메시지 내용'),
        ),
    ]
